### ISSUE TITLE
Web - Error: MissingPluginException(No implementation found for method write on channel plugins.it_nomads.com/flutter_secure_storage)

### ISSUE THREAD

**Issue by ValentinVignal** [juliansteenbakker/flutter_secure_storage#410]
I'm using flutter on chrome (incognito tab on localhost during the debug).

When I run:
```dart
const FlutterSecureStorage().write(
  key: 'myKey',
  value: 'myValue',
);
```

I get the error

```
Error: MissingPluginException(No implementation found for method write on channel plugins.it_nomads.com/flutter_secure_storage)
    at Object.throw_ [as throw] (http://localhost:52707/dart_sdk.js:5080:11)
at MethodChannel._invokeMethod (http://localhost:52707/packages/flutter/src/services/restoration.dart.lib.js:1567:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:52707/dart_sdk.js:40641:33
    at _RootZone.runUnary (http://localhost:52707/dart_sdk.js:40511:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:52707/dart_sdk.js:35438:29)
    at handleValueCallback (http://localhost:52707/dart_sdk.js:35999:49)
    at _Future._propagateToListeners (http://localhost:52707/dart_sdk.js:36037:17)
    at [_completeWithValue] (http://localhost:52707/dart_sdk.js:35872:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:52707/dart_sdk.js:35906:35)
    at Object._microtaskLoop (http://localhost:52707/dart_sdk.js:40778:13)
    at _startMicrotaskLoop (http://localhost:52707/dart_sdk.js:40784:13)
    at http://localhost:52707/dart_sdk.js:36261:9
```

I'm using the version `5.0.2`, flutter `3.0.3`

I saw the issues https://github.com/mogol/flutter_secure_storage/issues/71 https://github.com/mogol/flutter_secure_storage/issues/136 https://github.com/mogol/flutter_secure_storage/issues/152, but they are all closed and it seems none of them are about the web.

**Comment by leocape** [comment]
Working for me after upgrading to 6.0.0 Flutter stable 3.3.4

**Comment by tigrenok00** [comment]
Same issue on web, it works in localhost but not in HTTPS in production, did you find a solution?

**Comment by Ruthvik2011** [comment]
Did you find any workaround ?

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.

**Comment by talkbiz** [comment]
Hello, issue still exist in production

**Comment by p-divita-salto** [comment]
We have the same issue

**Comment by juliansteenbakker** [comment]
Hi all, i have released v10.0.0 which is a huge rewrite for most platforms. Please let me know if the issue still exists in this version.
