### ISSUE TITLE
v7.0.1 PlatformException(Exception encountered, readAll, java.lang.SecurityException: Could not decrypt key. decryption failed

### ISSUE THREAD

**Issue by meomap** [juliansteenbakker/flutter_secure_storage#501]
Hello, I think the option `encryptedSharedPreferences: true` works for `read` but not `readAll`. I can read value by specific key but cannot retrieve all values. 

Errors thrown on some devices Android version 11, 12, 13. 

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(Exception encountered, readAll, java.lang.SecurityException: Could not decrypt key. decryption failed
	at androidx.security.crypto.EncryptedSharedPreferences.decryptKey(EncryptedSharedPreferences.java:7)
	at androidx.security.crypto.EncryptedSharedPreferences.getAll(EncryptedSharedPreferences.java:4)
	at p9.a.l(FlutterSecureStorage.java:2)
	at p9.e$b.run(FlutterSecureStoragePlugin.java:13)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.security.GeneralSecurityException: decryption failed
	at o4.c$a.b(DeterministicAeadWrapper.java:15)
	at androidx.security.crypto.EncryptedSharedPreferences.decryptKey(EncryptedSharedPreferences.java:4)
	... 8 more
, null). Error thrown depricated2.exportAll error
error:PlatformException(Exception encountered, readAll, java.lang.SecurityException: Could not decrypt key. decryption failed
	at androidx.security.crypto.EncryptedSharedPreferences.decryptKey(EncryptedSharedPreferences.java:7)
	at androidx.security.crypto.EncryptedSharedPreferences.getAll(EncryptedSharedPreferences.java:4)
	at p9.a.l(FlutterSecureStorage.java:2)
	at p9.e$b.run(FlutterSecureStoragePlugin.java:13)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.security.GeneralSecurityException: decryption failed
	at o4.c$a.b(DeterministicAeadWrapper.java:15)
	at androidx.security.crypto.EncryptedSharedPreferences.decryptKey(EncryptedSharedPreferences.java:4)
	... 8 more
, null).
```

**Comment by tijee** [comment]
Yes, same error for me with `EncryptedSharedPreferences .getAll`.

**Comment by meomap** [comment]
@tijee We've already migrated from this lib. It's too painful when you have a large user base. 😓 If I remember correctly, instead of `readAll`, we use `read` on all keys that we've already indexed elsewhere.

**Comment by mellowcello77** [comment]
Just to confirm: so we should not enable encryptedSharedPreferences: true when using readAll()? 

(I am using readAll as a workaround for the cannot find key issue that popped up 5 days ago that is still open, and now this new error came up under our Android 14 users)

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.

**Comment by GiuseppeMaffiaAlten** [comment]
Hello, issue still exists. i enabled encryptedSharedPreferences and i'using readAll() method.. Any update?

**Comment by juliansteenbakker** [comment]
I have tried this with the example app:

1. Add aOptions with `encryptedSharedPreferences: true` to every function
2. write a key
3. remove aOptions from readAll function
4. restart app
5. I cant read any keys.
6. When i add aOptions back and restart again, i can read everything.

Can you also try this? Or do you have any steps on how to reproduce this behaviour?

**Comment by GiuseppeMaffiaAlten** [comment]
Thanks for the quick reply. 
I tried with your workaround and it work on debug mode. but the problem still exists on release mode. 
The only way to get around this problem is to clear the app cache after the first launch. Doing so also makes the call to readAll work properly. But the point is that I can't publish the app specifying to the end user to do this step in order to use it :sweat_smile:. 
It seems that when FlutterSecureStorage is initialized it writes something unencrypted, but on my side I'm sure I have enabled encryptedSharedPreferences on all the methods I use

**Comment by juliansteenbakker** [comment]
Are you sure you have added the options to all instances? If not, this can be a problem: https://github.com/juliansteenbakker/flutter_secure_storage/issues/837#issuecomment-2547868950

**Comment by GiuseppeMaffiaAlten** [comment]
To give you more context, in my case I created a CustomSecureStorage that extends FlutterSecureStorage. Here's an example of how I use it:

import 'package:flutter_secure_storage/flutter_secure_storage.dart';

class CustomSecureStorage extends FlutterSecureStorage {
  CustomSecureStorage() : super(aOptions: _getAndroidOptions());

  static AndroidOptions _getAndroidOptions() {
    return const AndroidOptions(
      encryptedSharedPreferences: true,
    );
  }

  Future<bool> isStorageClean() async {
    var allValues = await super.readAll(aOptions: _getAndroidOptions());
    return allValues.isEmpty;
  }

  Future<void> writeSomeKey(String someKey) async {
    await super.write(key: 'SomeKey', value: someKey, aOptions: _getAndroidOptions());
  }

  Future<String?> get getSomeKey async => await super.read(key: 'SomeKey', aOptions: _getAndroidOptions());

  Future<void> deleteSomeKey() async{
    await super.delete(key: 'SomeKey', aOptions: _getAndroidOptions());
  }

  Future<void> clearStorage() async{
    await super.deleteAll(aOptions: _getAndroidOptions());
  }
}

**Comment by GiuseppeMaffiaAlten** [comment]
> Are you sure you have added the options to all instances? If not, this can be a problem: [#837 (comment)](https://github.com/juliansteenbakker/flutter_secure_storage/issues/837#issuecomment-2547868950)

Yes I'm sure of that.

**Comment by juliansteenbakker** [comment]
I have tried your implementation both on develop and release mode, and i always get false on isStorageClean when i save a key, close the app and reopen it. I've tried this with a new empty flutter app. Do you have the same result in a new clean flutter app?

**Comment by GiuseppeMaffiaAlten** [comment]
Yes, I also tried with a new empty flutter app and I have the same result. Another information that I did not give you is that the end user in this case has a XIAOMI REDMI NOTE 13 PRO 5G. Is it possible that this problem occurs only for the operating system that the REDMI has?

**Comment by juliansteenbakker** [comment]
That could be, but i still dont know really how that could happen. It's very hard to debug this, as i do not have a Xiaomi phone. Did you also try it using the latest beta version v10.0.0-beta.1? That version migrates everything to encryptedSharedPreferences, and has lots of other improvements.

**Comment by juliansteenbakker** [comment]
Please read the following about this issue: https://github.com/juliansteenbakker/flutter_secure_storage?tab=readme-ov-file#android
 
Add the following to your android/app/src/main/AndroidManifest.xml:

<application android:allowBackup="false" ...>

**Comment by GiuseppeMaffiaAlten** [comment]
I tried with both solutions and with the prop android:allowBackup="false" work correctly. Thank you so much @juliansteenbakker for support!

**Comment by juliansteenbakker** [comment]
No problem! The new version 10.0 will have updated documentation about this.
