### ISSUE TITLE
[Android] [Beta] Version 10 - Full migration to custom implementation of SecureSharedPreferences

### ISSUE THREAD

**Issue by juliansteenbakker** [juliansteenbakker/flutter_secure_storage#769]
A long outstanding problem with the Android part of this package is the deprecated usage of older cryptography usage (CBC with PKCS5/PKCS7 padding) for SDK < 23, and the already deprecated JetSec Crypto library that is being used for the current implementation of SecureSharedPreferences.

To fix these issues, i am moving to a custom implementation of the JetSec Crypto library, and removing all other deprecated methods of encrypting the shared preferences. This requires the minimum SDK to be raised from 21 to 23.

I am currently testing the new implementation in the [branch `version-10`](https://github.com/mogol/flutter_secure_storage/tree/version-10). Any help is greatly appreciated.

Affected issues:
#512 #522 #562 #584 #627 #672 #694 #713 #729 #758 #759

**Comment by paulking86** [comment]
Hi @juliansteenbakker - Thanks for your work on this!

Have just tested the `version-10` branch using the override for `flutter_secure_storage_web: ^2.0.0-beta.1`.

When running the app on a device which has written to secure storage prior to this upgrade, my app crashes on startup (when I call `readAll()`). Here is the traceback:

```
PlatformException(Exception encountered, readAll, java.lang.SecurityException: Could not decrypt key. decryption failed
	at com.it_nomads.fluttersecurestorage.crypto.EncryptedSharedPreferences.decryptKey(EncryptedSharedPreferences.java:566)
	at com.it_nomads.fluttersecurestorage.crypto.EncryptedSharedPreferences.getAll(EncryptedSharedPreferences.java:377)
	at com.it_nomads.fluttersecurestorage.FlutterSecureStorage.readAll(FlutterSecureStorage.java:54)
	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:156)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
Caused by: java.security.GeneralSecurityException: decryption failed
	at com.google.crypto.tink.daead.DeterministicAeadWrapper$WrappedDeterministicAead.decryptDeterministically(DeterministicAeadWrapper.java:122)
	at com.it_nomads.fluttersecurestorage.crypto.EncryptedSharedPreferences.decryptKey(EncryptedSharedPreferences.java:557)
	... 8 more
```

If I uninstall the previous version of my app (using `9.2.2`) and perform a clean install (using `version-10`), then the app appears to work as expected.

This is using a physical Google Pixel 7 pro on Android 15, Flutter 3.22.3. Have yet to try on iOS but will do that later. If there is any other information you need or anything you want me to try, do let me know! :+1:

**Comment by paulking86** [comment]
Can confirm that this issue does not occur on iOS. This is also a physical device (iPhone 12), iOS 16, Flutter 3.22.3. `version-10` appears to be behaving and I have yet to observe any keychain related errors. 💪

**Comment by juliansteenbakker** [comment]
> This is using a physical Google Pixel 7 pro on Android 15, Flutter 3.22.3. Have yet to try on iOS but will do that later. If there is any other information you need or anything you want me to try, do let me know! 👍

Did you set the `encryptedSharedPreferences` to true, or didnt you use it at all?

**Comment by paulking86** [comment]
Instantiated with defaults!

`final storage = new FlutterSecureStorage();`

Will try with encrypted preferences on now :+1:

**Comment by paulking86** [comment]
No problem @juliansteenbakker - I can confirm that upgrading from `9.2.2` with encrypted prefs to `10` also using encrypted prefs appears to work as expected 🙌

**Comment by sed1ka** [comment]
Hi @juliansteenbakker thanks for your work!

When will version 10 be released?
Suppose it can't be estimated. Can it be published in pre-release?

**Comment by Gonzalo-Bruna** [comment]
I wish we could have some news about this, I still can't fix the issue on many devices, and I might have to use another library for now. Any updates on the progress?

**Comment by acacioveit** [comment]
any updates here guys? thank you very much in advance

**Comment by bahadirarslan** [comment]
> I wish we could have some news about this, I still can't fix the issue on many devices, and I might have to use another library for now. Any updates on the progress?

I am dropping this package because of this problem. I hope one day you can fix it and we can return.

**Comment by acacioveit** [comment]
Yeah @bahadirarslan, I'm also thinking about that, even downgrading to version 6 it is not working in many devices here in our application :(

**Comment by juliansteenbakker** [comment]
Hi all, i have been working on a migration which i am testing right now. Once done, i will release this under a new beta version.

**Comment by dharanidharandharmasivam** [comment]
@juliansteenbakker , could you please provide an approximate timeline for this beta release, so that I can plan accordingly for my project?

**Comment by ernestjsf** [comment]
Is there any update about this issue? Any estimated time frame for when it will be fixed?

**Comment by juliansteenbakker** [comment]
Hi all, i have worked on a version with migration support. The timeline is as follow:

v10.0.0: version with custom implementation of secure storage, together with a migration tool. This version will still have the insecure encryption method for when `useEncryptedSharedPreferences` is disabled.

v11.0.0: old encryption method will be removed and only the new encrypted shared preference will be used.

If you want users to keep their data, you should first upgrade to version 10.0.0 and when feeling confident that everyone is migrated, update to version 11.0.0. Otherwise, you can use version 11.0.0 straight away

As some may have noticed, the package is now part of my github page, which enables me to rearrange the issues and braches. I am planning on reviving support for this package as soon as i am back from my vacation, which is around 16 december. Version 10.0.0 will be released in that week, and version 11.0.0 will soon follow as it only removes the deprecated code and migration tool.

My apologies for the delay.

**Comment by daniloapr** [comment]
Looking forwad to this!

**Comment by kieranmccwayleadr** [comment]
Bump

**Comment by GelistirmeKF** [comment]
Hi, is there any update about Version 10? Thanks in advance

**Comment by dharanidharandharmasivam** [comment]
Hi @juliansteenbakker , could you please provide an updated timeline for version 10? We are anticipating this release.

**Comment by juliansteenbakker** [comment]
Hi, i am almost done with the first beta release of version 10. I am planning on releasing the beta version today or tomorrow. In the mean time, i have released v9.2.3 which has some minor improvements.

**Comment by juliansteenbakker** [comment]
I have released v10.0.0-beta.1, which contains a migration tool to copy data to EncryptedSharedPreferences, together with lots of other improvements. Please checkout the full list in the changelog.

If the beta version has no problems for users, i will promote it to a stable release.

**Comment by vladimir-boyko** [comment]
Hi @juliansteenbakker, what's your plans on release date of v10.0.0?

**Comment by juliansteenbakker** [comment]
I am still working on a better integration of the new Tink API but i am aiming on another week of development before i get my final beta release, and when the beta release is deemed stable, i can promote it to production. In all i'm aiming on a new production version at the end of this month.

**Comment by ricardodalarme** [comment]
Hey @juliansteenbakker any updated on this?

**Comment by juliansteenbakker** [comment]
"Due to limited resources on my end, I haven't had the time to make a stable release or address any potential issues that might arise from it. However, I am still working on this new release."

**Comment by sherlockvn** [comment]
While waiting for new update from @juliansteenbakker , i remove the `AES_CBC_PKCS7Padding` in the code, so that when analysis with Mobsf i will pass with this fork: [My fork](https://github.com/sherlockvn/flutter_secure_storage/tree/remove-old-encrypt-algorithm)

**Comment by AndresCM12** [comment]
@sherlockvn Hey, I have tried to use your fork, but I get an error with the name of the package. Can you provided an example of how can I import this package through the pubspec.yaml.
`  flutter_secure_storage:
    git:
      url: https://github.com/sherlockvn/flutter_secure_storage.git
      ref: remove-old-encrypt-algorithm
  flutter_secure_storage_linux: ^1.2.2
  flutter_secure_storage_macos: ^3.1.3
  flutter_secure_storage_platform_interface: 1.1.2
  flutter_secure_storage_web: 1.2.1
  flutter_secure_storage_windows: 3.1.2`

Gives: 
Error on line 1, column 7: "name" field doesn't match expected name "flutter_secure_storage".
  ╷
1 │ name: flutter_secure_storage_root

Also I tried to import with the root, but I was not able to import the code into my project.

**Comment by karthik-gowda** [comment]
@AndresCM12 even am getting the same error, @sherlockvn any solution you have here

**Comment by GelistirmeKF** [comment]
Hi @juliansteenbakker, what's your plan about final release date of v10.0.0?

**Comment by sherlockvn** [comment]
hi @AndresCM12 use this import it will work fine
```
flutter_secure_storage:
    git:
      url: https://github.com/sherlockvn/flutter_secure_storage.git
      ref: remove-old-encrypt-algorithm
      path: flutter_secure_storage
```

**Comment by GameOnAnil** [comment]
[912](https://github.com/juliansteenbakker/flutter_secure_storage/issues/912) This seems to be a breaking issue as i have many user using previous encryption and cannot upgrade without proper migration step.

**Comment by TheOneWithTheBraid** [comment]
I'm experiencing issues with missing classes, I opened #937 about this. Is there anything one will need to change about the Proguard rules with the beta version ?

**Comment by su-sd** [comment]
What is the status here? `flutter pub outdated` shows a lot of the dependencies of `flutter_secure_storage`.

@bahadirarslan What package do you use now?

**Comment by GelistirmeKF** [comment]
Hi @juliansteenbakker,

I would like to thank to you for providing this useful package to us. Nowadays, we are preparing a deployment plan for our app, is there a plan for Version 10?

Kindly Regards,
KF

**Comment by ilpeppone7** [comment]
Hi @juliansteenbakker 
due to the recent EncryptedSharedPreferences deprecation, are there any plans for a migration of this encryption method? If there are, could you please share what the new encryption system will be and when you're planning to release it?
Thank you :D

**Comment by RishabJaiswal** [comment]
Any possible update on this?! We stilling facing MobSF scan issues.

**Comment by juliansteenbakker** [comment]
Apologies for the delay. A significant amount of time was invested in resolving compatibility issues with the Jetpack Security library, which has since been deprecated. I subsequently attempted a transition to the Google Tink library, but its lack of biometric support required a full refactor of the Android implementation. This proved time-consuming, together with limited availability over the past months due to the birth of my son.

That said, the new beta release is nearing completion. Over the coming days I will finalize a few remaining updates. This new beta version addresses all current concerns within the native Android layer, including a return to custom cipher implementations and the deprecation of both Tink and Jetpack Security (now retained solely for migration purposes). It also introduces migration tooling to support seamless data transfer.

The latest status is available under #1002.

**Comment by juliansteenbakker** [comment]
I've released v10.0.0-beta.5, which includes a migration tool for data stored with 9.2.4 as well as v10.0.0-beta.4, together with many other things which are in the changelog. Would be nice to get some feedback on this version so i can release it asap 😃

**Comment by hai-trung-le** [comment]
I upgraded from v10.0.0-beta.4 to v10.0.0-beta.5 without any issues (though my usage is fairly small).

**Comment by Vukan-Levi9** [comment]
@juliansteenbakker when we can expect v10.0.0-beta.5 to become stable?

**Comment by juliansteenbakker** [comment]
Beta.5 is now out two weeks, and i haven't heard any issues regarding this release. I will try to merge the last open pull requests asap, and i'm planning on a stable release later this week.

**Comment by juliansteenbakker** [comment]
[I have released v10.0.0](https://github.com/juliansteenbakker/flutter_secure_storage/releases/tag/v10.0.0)

Thank you all for your patience!

**Comment by dharanidharandharmasivam** [comment]
Hi @juliansteenbakker ,

Yet I have noticed the following issue in the latest version (v10.0.0). Could you please investigate why this has occurred despite using the most recent release?

Please note that my app's minimum sdk version is 29.

<img width="1433" height="143" alt="Image" src="https://github.com/user-attachments/assets/f9c35755-16d2-4236-8d8a-a1b63dcfcb09" />

<img width="1461" height="712" alt="Image" src="https://github.com/user-attachments/assets/c741b9bb-56d9-4141-b6bd-e558ba92d157" />

**Comment by Clothless** [comment]
@dharanidharandharmasivam 
Am facing the same issue, I've updated to the latest v10.0.0 and my min sdk is 26

<img width="1678" height="106" alt="Image" src="https://github.com/user-attachments/assets/2346dca5-5669-4f93-9398-ee487731f451" />


Any updates on this is appreciated
