### ISSUE TITLE
[iOS] Failed to build iOS app when add flutter_secure_storage

### ISSUE THREAD

**Issue by rafaelgcs** [juliansteenbakker/flutter_secure_storage#823]
I added the flutter_secure_storage and when i tried to run the app, received the error with Flutter/Flutter.h

When i remove the flutter_secure_storage, the app run normally 

Anyone have one solution for this?

> flutter run --verbose:
```

[  +20 ms] Failed to build iOS app
[   +3 ms] Error (Xcode): double-quoted include "FlutterSecureStoragePlugin.h" in
framework header,
           expected angle-bracketed instead

/Users/rafaelgcs/Projects/cantinapass/cantinapass/ios/Pods/Target%20Support%20Files/flut
           ter_secure_storage/flutter_secure_storage-umbrella.h:12:8
           
[   +2 ms] Error (Xcode): 'Flutter/Flutter.h' file not found

/Users/rafaelgcs/.pub-cache/hosted/pub.dev/flutter_secure_storage-9.2.2/ios/Classes/Flut
           terSecureStoragePlugin.h:10:8
           
[        ] Error (Xcode): (fatal) could not build module 'flutter_secure_storage'

/Users/rafaelgcs/Library/Developer/Xcode/DerivedData/Runner-apsenvcayswpcqdqagintmtvktzx

/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/flutter_secure_storage.bui

ld/VerifyModule/flutter_secure_storage_objective-c++_arm64-apple-ios12.0-simulator_gnu++
           20/Test/Test.framework/Headers/Test.h:0:8
           
[        ] Error (Xcode): (fatal) could not build module 'Test'

/Users/rafaelgcs/Library/Developer/Xcode/DerivedData/Runner-apsenvcayswpcqdqagintmtvktzx

/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/flutter_secure_storage.bui

ld/VerifyModule/flutter_secure_storage_objective-c++_arm64-apple-ios12.0-simulator_gnu++
           20/Test/Test.mm:0:8
           
[        ] Error (Xcode): (fatal) could not build module 'flutter_secure_storage'

/Users/rafaelgcs/Library/Developer/Xcode/DerivedData/Runner-apsenvcayswpcqdqagintmtvktzx

/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/flutter_secure_storage.bui

ld/VerifyModule/flutter_secure_storage_objective-c++_x86_64-apple-ios12.0-simulator_gnu+
           +20/Test/Test.framework/Headers/Test.h:0:8
           
[        ] Error (Xcode): (fatal) could not build module 'Test'

/Users/rafaelgcs/Library/Developer/Xcode/DerivedData/Runner-apsenvcayswpcqdqagintmtvktzx

/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/flutter_secure_storage.bui

ld/VerifyModule/flutter_secure_storage_objective-c++_x86_64-apple-ios12.0-simulator_gnu+
           +20/Test/Test.mm:0:8
           
[        ] Error (Xcode): (fatal) could not build module 'flutter_secure_storage'

/Users/rafaelgcs/Library/Developer/Xcode/DerivedData/Runner-apsenvcayswpcqdqagintmtvktzx

/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/flutter_secure_storage.bui

ld/VerifyModule/flutter_secure_storage_objective-c_arm64-apple-ios12.0-simulator_gnu17/T
           est/Test.framework/Headers/Test.h:0:8
           
[        ] Error (Xcode): (fatal) could not build module 'Test'

/Users/rafaelgcs/Library/Developer/Xcode/DerivedData/Runner-apsenvcayswpcqdqagintmtvktzx

/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/flutter_secure_storage.bui

ld/VerifyModule/flutter_secure_storage_objective-c_arm64-apple-ios12.0-simulator_gnu17/T
           est/Test.m:0:8
           
[        ] Error (Xcode): (fatal) could not build module 'flutter_secure_storage'

/Users/rafaelgcs/Library/Developer/Xcode/DerivedData/Runner-apsenvcayswpcqdqagintmtvktzx

/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/flutter_secure_storage.bui

ld/VerifyModule/flutter_secure_storage_objective-c_x86_64-apple-ios12.0-simulator_gnu17/
           Test/Test.framework/Headers/Test.h:0:8
           
[        ] Error (Xcode): (fatal) could not build module 'Test'

/Users/rafaelgcs/Library/Developer/Xcode/DerivedData/Runner-apsenvcayswpcqdqagintmtvktzx

/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/flutter_secure_storage.bui

ld/VerifyModule/flutter_secure_storage_objective-c_x86_64-apple-ios12.0-simulator_gnu17/
           Test/Test.m:0:8
           
[   +3 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 16.
[   +3 ms] "flutter run" took 166,123ms.
[  +42 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand
(package:flutter_tools/src/commands/run.dart:874:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
           
           
[ +254 ms] ensureAnalyticsSent: 251ms
[        ] Running 2 shutdown hooks
[   +3 ms] Shutdown hooks complete
[   +8 ms] exiting with code 1 

```

**Comment by rafaelgcs** [comment]
> Please try updating your CocoaPods version.
> 
> > Error (Xcode): double-quoted include "FlutterSecureStoragePlugin.h" in framework header, expected angle-bracketed instead
> 
> This error occurs because the default option for `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` was set to true starting from Xcode 12. CocoaPods has already addressed this issue: [CocoaPods/CocoaPods#9902 (comment)](https://github.com/CocoaPods/CocoaPods/issues/9902#issuecomment-694909508)

Thanks, @y-aut!

solved to me:

1. Removed CocoaPods of my mac
2. Installing cocoapods using brew `brew install cocoapods`
3. Removed ios folder of my project
4. `cd ..` in root folder
5. `flutter create <project_name>`

Then flutter run and the project run normally
