### ISSUE TITLE
NullPointerException trying to call write() on some Android devices

### ISSUE THREAD

**Issue by brandon-watkins-avcrm** [juliansteenbakker/flutter_secure_storage#832]
Running into this problem on a DJI Smart Controller running Android 7.1.2

Error below:

```
PlatformException(Exception encountered, write, java.lang.NullPointerException: Attempt to invoke interface method 'byte[] com.it_nomads.fluttersecurestorage.ciphers.o.a(byte[])' on a null object reference
	at i6.a.p(SourceFile:28)
	at i6.e$b.run(SourceFile:298)
	at android.os.Handler.handleCallback(Handler.java:755)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:167)
	at android.os.HandlerThread.run(HandlerThread.java:61)
, null)
```

**Comment by juliansteenbakker** [comment]
Please try with our latest beta version 10.0.0-beta.2, and let me know if the issue is still there.
